### ISSUE TITLE
Error in labo_train.sh

### ISSUE THREAD

**Issue by Susmit-A** [YueYANG1996/LaBo#1]
I get the following error:

```
main.py: error: argument --func: expected one argument
```

Examining the script and the code, the value of `$asso_opt_main` is undefined in `labo_train.sh` and the `eval()` function in `main.py` is also undefined.

**Comment by YueYANG1996** [comment]
asso_opt_main is the function name and doesn't require any value.
[eval()](https://realpython.com/python-eval-function/) is the built-in function of python.

**Comment by Susmit-A** [comment]
Thanks for the response, had to remove the "$" symbol before asso_opt_main in the train bash script.

I'm also getting the following error when running in line 163 of submodular_select:
"ValueError: X cannot contain negative values or must be entirely negative values."
This is for the features in path "exp/asso_opt/CIFAR10/CIFAR10_allshot_fac/concepts_feat_ViT-L-14.pth"

**Comment by YueYANG1996** [comment]
I have this error before and I fixed it by modifying the source file of the apricot package. You can change the [line 202](https://github.com/jmschrei/apricot/blob/bf86e699e6929127ccb5876d8c62c70785390eb0/apricot/functions/base.py#L202) of the base.py in the error message to make it can take in negative values.

**Comment by Susmit-A** [comment]
Thank you for the prompt resolution!
