### ISSUE TITLE
cant train with the dataset cifar10 and cifar100

### ISSUE THREAD

**Issue by Adasunnylily** [YueYANG1996/LaBo#10]
hi, I used the code you provided in issue4 to deal with cifar10 and cifar100, but I still got the error for both dataset training

I got the error for cifar10
Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: ' /LaBo/datasets/CIFAR10/images/stealth_bomber_s_000554.png'
  File " /LaBo/utils.py", line 88, in <listcomp>
    img_tensor = torch.cat([preprocess(Image.open('{}'.format(img_name)))\
  File " /LaBo/utils.py", line 88, in process_img
    img_tensor = torch.cat([preprocess(Image.open('{}'.format(img_name)))\
  File " /LaBo/utils.py", line 62, in batchify_run
    batch_res = process_fn(batch_data)
  File " /LaBo/utils.py", line 98, in prepare_img_feat
    batchify_run(process_img, img_names, res, 1024, use_tqdm=True)
  File "/ /LaBo/data.py", line 306, in compute_img_feat
    img_feat = utils.prepare_img_feat(all_img_paths,
  File " /LaBo/data.py", line 320, in prepare_img_feat
    img_feat, label = self.compute_img_feat(cls2img, n_shots if mode == 'train' else 'all', clip_model, clip_ckpt)
  File " /LaBo/data.py", line 158, in __init__
    self.prepare_img_feat(self.splits, self.n_shots, self.clip_model, self.clip_ckpt)
  File " /LaBo/main.py", line 205, in asso_opt_main
    data_module = DataModule(
  File " /LaBo/main.py", line 356, in <module>
    main(cfg)
FileNotFoundError: [Errno 2] No such file or directory: ' /LaBo/datasets/CIFAR10/images/stealth_bomber_s_000554.png'

and the error for cifar100
[Errno 2] No such file or directory: ' /LaBo/datasets/CIFAR100/images/eating_apple_s_000763.png'

**Comment by YueYANG1996** [comment]
This is the error for file not found, could you check if those files are in these directories?

**Comment by Adasunnylily** [comment]
They are not in the directories but in the class2images_train.p which is conducted in the code you provided, I am really confused

**Comment by Adasunnylily** [comment]
I used the provided code to process the data but still got files not found error, and they truly not exist in the directory.
Could you please provide the processed cifar10 and cifar100 datasets that could be used for training?
It will be really helpful, thanks a lot!!!

**Comment by YueYANG1996** [comment]
If you successfully ran the processing code, where did you save the processed images? If they are not in the directory mentioned in the error message, then move them there.
