### ISSUE TITLE
Query regarding selecting concept in Figure 7

### ISSUE THREAD

**Issue by tfc-0** [YueYANG1996/LaBo#11]
Hi,

In Figure 7 of the [paper](https://openaccess.thecvf.com/content/CVPR2023/papers/Yang_Language_in_a_Bottle_Language_Model_Guided_Concept_Bottlenecks_for_CVPR_2023_paper.pdf), you have mentioned that: 

> The top-3 concepts, ranked by their weights in the linear function, for randomly selected classes, paired with a random image from the class, across 6 datasets.

So, did you select the top-3 concepts for a predicted class's set of concepts from [mat](https://github.com/YueYANG1996/LaBo/blob/main/models/asso_opt/asso_opt.py#L231), not from [dot_product](https://github.com/YueYANG1996/LaBo/blob/main/models/asso_opt/asso_opt.py#L232)? Am I right here?

**Comment by YueYANG1996** [comment]
Yes, you're right.
