### ISSUE TITLE
concept generation for custom dataset

### ISSUE THREAD

**Issue by tfc-0** [YueYANG1996/LaBo#12]
Hi,

Can you share code for generating concepts for custom dataset in your repository?

**Comment by YueYANG1996** [comment]
Hi,

We were using the following 5 prompt template with OpenAI's API to get the concepts.

```prompts = ["Use 10 sentences to describe how the {} looks like:\n1)",
           "Use 10 sentences to describe the appearance of the {}:\n1)",
           "Use 10 sentences to describe the color of the {}:\n1)",
           "Use 10 sentences to describe the pattern of the {}:\n1)",
           "Use 10 sentences to describe the shape of the {}:\n1)"]
```

Feel free to use your own prompt and make sure the data structure of class2concepts.json is a dictionary with key as class name and value is a list of concepts like [this](https://github.com/YueYANG1996/LaBo/blob/main/datasets/CIFAR10/concepts/class2concepts.json).
