### ISSUE TITLE
Cifar10 & cifar100 datasets problem

### ISSUE THREAD

**Issue by algpy** [YueYANG1996/LaBo#15]
Hi,

Sorry to disturb you. I encountered the following error while trying to run the code on the cifar dataset.

> FileNotFoundError: [Errno 2] No such file or directory: ‘~/LaBo/datasets/CIFAR100/images/access_road_s_001073.png

It seems the program is looking for data in PNG format. However, the cifar download link provided in the dataset.md is not in PNG format but consists of three files. Here I am curious about where the cifar dataset used by the program comes from or how it is generated.

Thanks!

**Comment by YueYANG1996** [comment]
Could you try this preprocessing code?

https://github.com/YueYANG1996/LaBo/issues/4

**Comment by algpy** [comment]
Thank you, this solved my issue!

**Comment by algpy** [comment]
Thank you, this solved my issue!

**Comment by algpy** [comment]
Thank you, this solved my issue!
