### ISSUE TITLE
sh labo_train.sh {DATASET} {SHOTS} does not match labo_train.sh

### ISSUE THREAD

**Issue by Wazhee** [YueYANG1996/LaBo#17]
In labo_train.sh you defined "cfg/asso_opt/$2/$2_$1shot_fac.py" as the config filepath.

If $1 is {Dataset} & $2 is {shots} as defined in the readme, the labo_train.sh should be defined as the following:

cfg/asso_opt/$1/$1_$2shot_fac.py

**Comment by YueYANG1996** [comment]
You are right, thanks! I just updated the readme.
