### ISSUE TITLE
Selected Concepts

### ISSUE THREAD

**Issue by 42x00** [YueYANG1996/LaBo#19]
Hello,

Thanks for sharing the code of your remarkable work. 

I'm writing to ask about the "50 selected concepts for each class" mentioned in your paper. Computing these for each dataset is resource-intensive, and having them directly would be a great help to the community.

Many thanks in advance!

Best,
Yikai

**Comment by YueYANG1996** [comment]
Hi Yikai,

Selecting 50 concepts using this codebase is very fast if you have precomputed all the features. But I will also provide the selected concepts using all training data in the repo shortly.

Yue

**Comment by YueYANG1996** [comment]
Sorry for the late reply, please see the data here: https://github.com/YueYANG1996/LaBo/tree/main/selected_concepts

**Comment by wenqian-ye** [comment]
Hi Yue, thanks a lot for providing the selected concepts! Could you also provide the instructions on how to generate the selected concepts at the Readme? It would be very helpful for us to run this procedure on other datasets.

**Comment by YueYANG1996** [comment]
> Hi Yue, thanks a lot for providing the selected concepts! Could you also provide the instructions on how to generate the selected concepts at the Readme? It would be very helpful for us to run this procedure on other datasets.

Please check [here](https://github.com/YueYANG1996/LaBo/issues/22#issuecomment-1887205713) for this question.
