### ISSUE TITLE
TypeError: __new__() missing 1 required positional argument: 'task'

### ISSUE THREAD

**Issue by FisherCats** [YueYANG1996/LaBo#23]
After fixing the error that negative value can't be received, this error comes subsequently: 
"""
use asso concept with dot product loader, faster
Traceback (most recent call last):
  File "/LaBo-main/main.py", line 350, in <module>
    main(cfg)
  File "/LaBo-main/main.py", line 270, in asso_opt_main
    model = AssoConceptFast(cfg, init_weight=th.load(cfg.init_weight_path) if 'init_weight_path' in cfg else None)
  File "/LaBo-main/models/asso_opt/asso_opt.py", line 68, in __init__
    self.train_acc = torchmetrics.Accuracy(num_classes=cfg.num_cls)
TypeError: __new__() missing 1 required positional argument: 'task'
"""

I didn't modify the whole code file, what's that mean? 
I'll be really appreciated if you could help me.
![image](https://github.com/YueYANG1996/LaBo/assets/53413123/9e51aa9b-eaca-4174-ab4f-410199ec2269)

**Comment by YueYANG1996** [comment]
Could you try adding `task='multiclass'` to each `torchmetrics.Accuracy()`? It seems to be the issue of pytorch version.

**Comment by FisherCats** [comment]
Thanks a lot, Yue, it's works. But there comes another error:
Traceback (most recent call last):
  File "/home/LaBo-main/main.py", line 350, in <module>
    main(cfg)
  File "/home/LaBo-main/main.py", line 270, in asso_opt_main
    model = AssoConceptFast(cfg, init_weight=th.load(cfg.init_weight_path) if 'init_weight_path' in cfg else None)
  File "/home/LaBo-main/models/asso_opt/asso_opt.py", line 74, in __init__
    self.confmat = torchmetrics.ConfusionMatrix(self.cfg.num_cls)
  File "/home/lib/python3.8/site-packages/torchmetrics/classification/confusion_matrix.py", line 519, in __new__
    task = ClassificationTask.from_str(task)
  File "/home/lib/python3.8/site-packages/torchmetrics/utilities/enums.py", line 45, in from_str
    me = super().from_str(value.replace("-", "_"), source=source)
AttributeError: 'int' object has no attribute 'replace'

and after that, I tried to fix the error by modifying the parameters like that:
![image](https://github.com/YueYANG1996/LaBo/assets/53413123/6730f82f-93bf-4fd6-88e5-c589ebfde406)
and it seems working but failed eventually:
![image](https://github.com/YueYANG1996/LaBo/assets/53413123/5d3bf9a2-8903-4fbf-bf01-36794ff50f66)
File "/home/LaBo-main/models/asso_opt/asso_opt.py", line 141, in validation_step
    wandb.define_metric('val_acc', summary='max')
  File "/home/lib/python3.8/site-packages/wandb/sdk/lib/preinit.py", line 36, in preinit_wrapper
    out = method(*_args, **_kwargs)
  File "/home/LaBo-main/models/asso_opt/asso_opt.py", line 141, in validation_step
    wandb.define_metric('val_acc', summary='max')
  File "/home/lib/python3.8/site-packages/wandb/sdk/lib/preinit.py", line 36, in preinit_wrapper
    raise wandb.Error(f"You must call wandb.init() before {name}()")
    raise wandb.Error(f"You must call wandb.init() before {name}()")
wandb.errors.Error: You must call wandb.init() before wandb.define_metric()
wandb.errors.Error: You must call wandb.init() before wandb.define_metric()
Sanity Checking DataLoader 0: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.68it/s]/home/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:433: It is recommended to use `self.log('val_loss', ..., sync_dist=True)` when logging on epoch level in distributed setting to accumulate the metric across devices.
[rank: 1] Child process with PID 645398 terminated with code 1. Forcefully terminating all other processes to avoid zombies 🧟
Killed

**Comment by YueYANG1996** [comment]
You need to log in to your wandb. 
https://docs.wandb.ai/ref/cli/wandb-login

**Comment by FisherCats** [comment]
It didn't work even I login my wandb account.
![image](https://github.com/YueYANG1996/LaBo/assets/53413123/ad542b4e-4bee-4b1a-9140-f451bf44e108)
same error as my last comment.
![image](https://github.com/YueYANG1996/LaBo/assets/53413123/52d4285e-a8df-402b-ac1e-5eb21d3bad8b)

**Comment by YueYANG1996** [comment]
Not sure why this is happening. Could be the package version issue.
could you try to install `wandb` and `pytorch-lightning` with the following versions?
https://github.com/YueYANG1996/LaBo/blob/83ed4b08912a63fcc8d006a97b3cd51ebdcc2cdb/environment.yml#L427
https://github.com/YueYANG1996/LaBo/blob/83ed4b08912a63fcc8d006a97b3cd51ebdcc2cdb/environment.yml#L386

**Comment by whalefall123456** [comment]
You should use torchmetrics ==0.9.1, and the program will be back to normal after I modified it.
