### ISSUE TITLE
Problem related to high LaBO training time

### ISSUE THREAD

**Issue by SwetaMahajan** [YueYANG1996/LaBo#24]
Hi! 

Does LaBo training use max_epochs each time i.e, 15k for CIFAR10 and 1000 for ImageNet? Because, as you mentioned in one of the [earlier issues](https://github.com/YueYANG1996/LaBo/issues/7#issuecomment-1688302350), 10 mins per epoch for ImageNet for 1000 epochs amounts to 7 days, which is quite a lot. 

Also, it would be great if you could please tell if the trained checkpoints are available?

**Comment by YueYANG1996** [comment]
Why one epoch will take 10 mins? After precomputing the features, one epoch should be less than 30 seconds. 1000 epochs will take 470 mins (see below) on a single RTX A6000.
<img width="1221" alt="Screenshot 2024-02-24 at 10 32 30 AM" src="https://github.com/YueYANG1996/LaBo/assets/38372825/8986380b-e1dc-4ff9-bc64-4eda5255fddc">
