### ISSUE TITLE
Requirement Text Installation Issue

### ISSUE THREAD

**Issue by guolipin** [YueYANG1996/LaBo#27]
"conda install --file requirement.txt" error: some unrelated packages included in the requirement.txt resulting an installation issue, such as alembic and alsa-lib.
Could you please check the problem?

**Comment by YueYANG1996** [comment]
Could you please refer to [this](https://github.com/YueYANG1996/LaBo/issues/14#issuecomment-1847983397)?

**Comment by guolipin** [comment]
Dear Yue,

I am sorry that I miss your email. Thank you so much for your help.

Regards,
Lipin
