### ISSUE TITLE
ValueError: X cannot contain negative values or must be entirely negative values

### ISSUE THREAD

**Issue by zhaojianaaa** [YueYANG1996/LaBo#8]
Hi, you work was great, but there was an error in submodular_select() for MixtureSelection training as the follows, could you please give me some advice for this error, thanks again.

(n1) zj@cad:~/tc5/LM$ python3 main.py --cfg cfg/asso_opt/flower/flower_1shot_fac.py --work-dir exp/asso_opt/flower/flower_1shot_fac --func asso_opt_main
/home/zj/n1/lib/python3.6/site-packages/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
use submodular
[10000000.0, 10]
use dot product dataloader
prepare txt feat
100%|███████████████████████████████████████████████████████████████████████████████████████| 195/195 [00:15<00:00, 12.38it/s]
select concept
  0%|                                                                                                 | 0/102 [00:00<?, ?it/s]191 25
  0%|                                                                                                 | 0/102 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 350, in <module>
    main(cfg)
  File "main.py", line 249, in asso_opt_main
    submodular_weights=cfg.submodular_weights
  File "/home/zj/tc5/LM/data.py", line 377, in __init__
    super().__init__(*args, **kwargs)
  File "/home/zj/tc5/LM/data.py", line 178, in __init__
    self.select_concept(self.concept_select_fn, self.img_feat['train'], self.concept_feat, self.n_shots, self.num_concept, self.concept2cls, self.clip_ckpt, self.num_images_per_class, self.submodular_weights)
  File "/home/zj/tc5/LM/data.py", line 267, in select_concept
    num_concepts, num_images_per_class, submodular_weights)
  File "/home/zj/tc5/LM/models/select_concept/select_algo.py", line 163, in submodular_select
    selected = selector.fit(augmented_concept_features).ranking
  File "/home/zj/n1/lib/python3.6/site-packages/apricot/functions/mixture.py", line 215, in fit
    sample_weight=sample_weight, sample_cost=sample_cost)
  File "/home/zj/n1/lib/python3.6/site-packages/apricot/functions/base.py", line 202, in fit
    raise ValueError("X cannot contain negative values or must be entirely "\
ValueError: X cannot contain negative values or must be entirely negative values.

**Comment by YueYANG1996** [comment]
check this: https://github.com/YueYANG1996/LaBo/issues/1#issuecomment-1583107414

**Comment by zhaojianaaa** [comment]
Thanks a lot for your response, is works.
